apiVersion: apps/v1
kind: Deployment
metadata:
  name: miniproject
  labels:
    app: miniproject
spec:
  replicas: 1
  selector:
    matchLabels:
      app: miniproject
  template:
    metadata:
      labels:
        app: miniproject
    spec:
      containers:
        - name: miniproject
          image: zmsdlfsktdma/miniproject:latest   # ğŸ‘‰ ì—¬ê¸°ì— ë„¤ Docker Hub ì•„ì´ë””
          imagePullPolicy: Always                     # í•­ìƒ ìµœì‹  ì´ë¯¸ì§€ë¡œ
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: FLASK_ENV
              value: production
            - name: PORT
              value: "5000"
      restartPolicy: Always

